# Generated by Django 5.1.3 on 2024-11-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='code_agence',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='ville',
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_carte', models.CharField(max_length=100, verbose_name='Nom de la Carte')),
                ('type_carte', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10, verbose_name='Type de Carte')),
                ('rip', models.CharField(max_length=20, unique=True, verbose_name='RIP')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Émission")),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='bnaapp.agence', verbose_name='Agence')),
            ],
        ),
    ]
